- name: MariaDB | Create a new pass for root user
  shell: openssl rand -base64 12 creates=/dmoraes/.my.cnf
  register: mysql_root_pass

- name: MariaDB | Display new pass in playbook  output
  debug:
    msg: "New root pass: {{mysql_root_pass.stdout}}"
  when: mysql_root_pass.changed

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: wp1
    password: "{{ mysql_root_pass.stdout }}"
    priv: '*.*:ALL,GRANT'
    host: "%"
    state: present
