- name: Instalando pacotes do MariaDB
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb-server
    - mariadb
    - MySQL-python
  notify: Restart mariadb
  when: ansible_facts['distribution'] == "CentOS"
  
- name: Instalando pacotes teste
  notify: Restart mariadb

- name: Enable service Mysql, and not touch the state
  service:
    name: mariadb
    enabled: yes
  notify: Restart mariadb
  when: ansible_facts['distribution'] == "CentOS"