- name: Instalando Mariadb-Server
  apt:
    pkg:
    - mariadb-server
    - mariadb-client
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  notify:  Restart Mysql
- name: Install Compose
  pip:
    executable: pip3
    name: 
        - mysql-connector-python
  notify:  Restart Mysql
