- name: Instalando pacotes do MariaDB
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb-server
    - mariadb
    - MySQL-python
  when: ansible_facts['distribution'] == "CentOS"
  notify:  Restart Mysql